[package]
name = "gb-asset-studio"
version = "0.0.96"
description = "GB Asset Studio"
authors = ["GB Asset Studio contributors"]
edition = "2021"

[lib]
name = "gb_studio_visual_asset_builder_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
